(()=>{
const T={
f1:['Kalmár Panzió','Punkt startowy. Zapiszcie jedno słowo, które ma opisywać ten wyjazd. To słowo wróci przy Gellércie, Operze i w finale.','Wybierzcie jedno słowo na ten wyjazd. Niech będzie krótkie i Wasze.'],
f2:['Citadella','Pierwsza wielka panorama: Dunaj rozdziela Budę i Peszt, a mosty układają miasto w jedną kompozycję. Spójrzcie także na układ ulic i dachów poniżej.','Wróćcie do słowa z Kalmára i zdecydujcie, czy ten widok do niego pasuje.'],
f3:['Góra Gellerta','Nie szukajcie tylko pocztówkowego kadru. Najciekawsze są często dachy, światła i fragmenty miasta między oczywistymi punktami.','Wybierzcie jeden detal z widoku. Zapamiętajcie go — wróci dziś wieczorem.'],
f4:['Rudas — nocne kąpanie','Wieczorne Rudas to zmiana tempa po spacerze: ciepła woda, kamień i nocne światło. To ma być spokojny finał pierwszego dnia.','Przed wejściem powiedzcie sobie słowo z Kalmára i detal z Gellérta. Potem 10 minut bez telefonów.'],
s1:['Kalmár → trasa dzienna','To świadomy start soboty: Buda, widoki, Dunaj, powrót do bazy i dopiero wieczorem Opera. Nie próbujcie przyspieszać wszystkiego.','Przypomnijcie słowo z piątku. Wybierzcie budynek, który najlepiej do niego pasuje.'],
s2:['Zamek Królewski','Dzisiejszy pałac jest efektem wielu warstw historii i powojennej odbudowy. Zamiast odhaczać plac, znajdźcie jedną linię, rytm albo proporcję fasady.','Zachowajcie jeden detal fasady. Przy Macieju poszukacie jego przeciwieństwa.'],
s3:['Kościół Macieja','Kolorowy dach działa z daleka, ale warto podejść bliżej do faktury, ornamentu i różnic między elementami.','Każde wybiera detal, którego drugie nie zauważyło. Nie zdradzajcie go jeszcze.'],
s4:['Batthyány tér','Tu Parlament pojawia się jako część krajobrazu, a nie tylko pojedynczy budynek. Zobaczcie, jak rzeka ustawia perspektywę.','Połączcie dwa wcześniejsze detale w jedno zdjęcie — Waszą prywatną pocztówkę.'],
s5:['Punkt widokowy na Parlament','Najlepszy kadr nie musi być najbardziej oczywisty. Zwróćcie uwagę na relację między jasnym kamieniem Parlamentu, wodą i mostami.','Z poprzedniego zdjęcia wybierzcie jeden element i znajdźcie trzy odcienie kamienia.'],
s6:['Most Małgorzaty','Most pokazuje Budapeszt jako miasto dwóch brzegów i wyspy pośrodku. To dobry moment na zwolnienie po intensywnej części trasy.','Wybierzcie jeden kolor z poprzedniego zadania i spróbujcie znaleźć go po obu stronach Dunaju.'],
s7:['Kalmár — ogarniamy się','To nie atrakcja, tylko ważny reset logistyczny. Prysznic, przebranie, woda i wyjście o czasie są częścią udanej soboty.','Wróćcie do słowa z piątku i jednego detalu z Gellérta. 17:30 = wyjście.'],
s8:['Węgierska Opera Państwowa','Opera ma działać wszystkimi zmysłami: architektura, światło, schody i scena. Przyjdźcie wcześniej, żeby nie oglądać jej wyłącznie w biegu.','Znajdźcie detal, który nawiązuje do czegoś zauważonego rano. Zachowajcie go jako detal soboty.'],
s9:['Szimpla / ruin bary','Po Operze zmieniacie język miasta: z reprezentacyjnej architektury na improwizowaną przestrzeń ruin barów. Nie ma tu obowiązku odhaczania kolejnych miejsc.','Martynka wybiera pierwszy lokal, Bartek następny. Przy wyborze wróćcie do Waszego słowa z piątku.'],
s10:['Wielka Synagoga Dohány','Monumentalna fasada stoi na styku architektury sakralnej i miejskiej reprezentacji. Obejrzyjcie ją spokojnie od strony ulicy.','Znajdźcie detal bardziej pałacowy niż sakralny i porównajcie go z Operą.'],
n1:['Kalmár','Niedziela ma jeden priorytet: Parlament. Wszystko przed nim ma zostawić Wam komfortowy margines czasu.','Każde mówi jeden detal z soboty bez patrzenia w zdjęcia. Potem ruszacie.'],
n2:['Most Łańcuchowy','Most jest jednym z symboli połączenia Budy i Pesztu. Lwy są celowo widocznym motywem — zapamiętajcie jednego.','Wybierzcie jednego lwa jako symbol dnia. Ten symbol wróci przy Parlamencie.'],
n3:['Parlament — zbiórka','To twardy checkpoint całej trasy. Nie dokładamy tu żadnych spontanicznych zadań ani przystanków. Liczy się punktualność.','Przypomnijcie sobie lwa. Teraz tylko wejście 12:45.'],
n4:['Cookie Beacon Brunch Basilica','Po Parlamencie potrzebujecie przerwy, a nie kolejnego egzaminu z turystyki. Jedzenie ma być częścią rytmu dnia.','Wybierzcie jedną rzecz spoza zwykłego zamówienia. Mały eksperyment po dużej atrakcji.'],
n5:['Bazylika św. Stefana','Kopuła i fasada są zaprojektowane bardzo osiowo, więc warto patrzeć na symetrię oraz powtarzalne detale.','Znajdźcie detal podobny do czegoś z Opery. Zobaczcie, jak dwa różne budynki rozwiązują podobny motyw.'],
n6:['Mama Goulash','To punkt na konkretny posiłek i odzyskanie energii. Nie ścigajcie się z zegarkiem, ale trzymajcie miejsce w planie.','Zamówcie coś, czego żadne z Was wcześniej nie jadło. Przy okazji nazwijcie najlepszy moment wyjazdu.'],
n7:['Ruin bary','Wieczór nie potrzebuje kolejnych obowiązków. Jeśli korzystacie z losowanej akcji, niech będzie dodatkiem do Waszego dnia, a nie jego osią.','Losujcie tylko wtedy, gdy macie ochotę. Jeśli akcja się pojawi, połączcie ją ze słowem z piątku albo najlepszym momentem niedzieli.'],
n8:['Kalmár — meta niedzieli','Trzy dni miasta powinny już mieć własne skojarzenia. Teraz nie zbieracie kolejnych punktów — zbieracie wspomnienia.','Każde mówi jedną rzecz, którą chce zachować z wyjazdu. Bez powtarzania odpowiedzi drugiej osoby.'],
m1:['Kalmár','Ostatni poranek zaczyna się bez presji. Wspólny obraz z poprzednich dni staje się motywem finału.','Wybierzcie wspólnie jedno zdjęcie lub obraz z wyjazdu, który mógłby być jego okładką.'],
m2:['Jaskinia Gellérta','Wracacie w okolice początku podróży, ale patrzycie już inaczej. To świadome domknięcie pierwszego motywu Gellérta.','Znajdźcie detal, który zaskakuje. Porównajcie go z detalem wybranym w piątek.'],
m3:['Zamek Vajdahunyad','To architektoniczny kolaż różnych epok i stylów. Właśnie dlatego świetnie działa jako ostatnia spokojna atrakcja przed zejściem do hali targowej.','Wybierzcie fragment jak z filmu i nadajcie mu tytuł nawiązujący do Waszego słowa z początku wyjazdu.'],
m4:['Central Market Hall','Ostatni miejski punkt powinien być praktyczny i lekki: spacer, zapachy, jedzenie i ewentualna pamiątka. Nie przeciążajcie finału.','Kupcie jedną małą rzecz jako „Budapeszt 2026”. Niech przypomina konkretną misję.'],
m5:['Lotnisko','Tu kończy się gra. Wszystkie wcześniejsze motywy — słowo, detale, lew, zdjęcia i misje — zamieniają się w jedno wspomnienie.','Każde wybiera jedno wspomnienie, jedną misję i następny wspólny weekend.']
};
function apply(){try{const f=document.querySelector('iframe');const d=f?.contentDocument?.querySelector('iframe')?.contentDocument;if(!d)return;d.querySelectorAll('.stop').forEach(c=>{const id=c.querySelector('.done input')?.getAttribute('onchange')?.match(/complete\(['"]([^'"]+)/)?.[1];const t=T[id];if(!t)return;const s=c.querySelector('.ans[id$="s"]'),fact=c.querySelector('.ans[id$="f"]'),m=c.querySelector('.ans[id$="m"]');if(s)s.innerHTML='<b>CO WIDZIMY?</b><br>'+t[0]+' — '+t[1];if(m)m.innerHTML='<b>MISJA</b><br>'+t[2]});}catch(e){console.log('content-v2',e)}}
window.addEventListener('load',()=>setTimeout(apply,250));setInterval(apply,1000);
})();
